### PR TITLE
Dynamically generate path to OpenWith viewer icons

### LINKED ISSUE #26: Bug: broken 'OpenWith` icons
From #23. As reported at https://github.com/ome/omero-web-zarr/pull/7#issuecomment-1436494328
The icons referred to in the public dir haven't been copied over to production deployment

cc @joshmoore

### PR DESCRIPTION
**Pull request by will-moore**
Fixes #26.

### CODE REVIEW

**Comment by will-moore** [comment]
@joshmoore I think that should fix production deployment.

The icons are working in the deploy preview (above) but they also did before (in the previous PR preview at https://deploy-preview-23--ome-ngff-validator.netlify.app/?source=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0062A/6001240.zarr)

The difference you can see is in that case, you have ```Viewer logo```
whereas in the preview above you have ```Viewer logo``` which should translate into the correct absolute URLs in production.

**Comment by joshmoore** [comment]
I'm not sure how to reliably test (which is probably also an issue). Merging since the current production version is broken and I'll re-test there.

**Comment by joshmoore** [comment]
No luck, @will-moore.

**Comment by will-moore** [comment]
Hmmm - OK, I'll dig a bit more... I guess I could also open a PR to revert back to before #23 if I don't find the answer soon...

**Comment by will-moore** [comment]
Asked a question at https://github.com/vitejs/vite/discussions/12121

**Pull request merged**
