### PR TITLE
Bioformats layout

### PR DESCRIPTION
**Pull request by will-moore**
For a bioformats2raw.layout, load the OME/METADATA.xml and show image names, with links to browse to them.

WIP:

Screenshot 2022-09-09 at 17 19 58

### CODE REVIEW

**Comment by joshmoore** [comment]
https://deploy-preview-13--ome-ngff-validator.netlify.app/?source=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/test-data/bf2raw/fake-series-2.zarr results in:

> Loading metadata: [/OME/METADATA.ome.xml](https://uk1s3.embassy.ebi.ac.uk/idr/zarr/test-data/bf2raw/fake-series-2.zarr//OME/METADATA.ome.xml)
> Error loading https://uk1s3.embassy.ebi.ac.uk/idr/zarr/test-data/bf2raw/fake-series-2.zarr//OME/METADATA.ome.xml: Not Found

due to the extra slash (`//`)

https://deploy-preview-13--ome-ngff-validator.netlify.app/?source=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/test-data/bf2raw/plate-rows-2.zarr stops at "loading..."

**Comment by will-moore** [comment]
@joshmoore Fixed links (and I ignore Bioformats2raw layout for plates).
Also, added a vizarr link to each Image

Screenshot 2022-09-15 at 13 14 39

**Comment by joshmoore** [comment]
> Also, added a vizarr link to each Image

That's a good idea for working around https://github.com/hms-dbmi/vizarr/issues/149 :+1:

**Comment by joshmoore** [comment]
Any other changes expected here, @will-moore ?

**Comment by will-moore** [comment]
No, I'm not planning to add anything else

**Comment by joshmoore** [comment]
Propose to release tomorrow as 0.3.0 along with https://github.com/ome/ngff/pull/112#pullrequestreview-1120170007

**Comment by will-moore** [comment]
@joshmoore I updated version to 0.3.0 and updated changelog

**Comment by will-moore** [comment]
@joshmoore it looks like something's gone wrong with the deploy as https://ome.github.io/ome-ngff-validator/?source=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.3/9836842.zarr is not showing this PR.
The netlify build is OK https://ome-ngff-validator.netlify.app/?source=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.3/9836842.zarr but deploy to gh-pages isn't?

Will look more tomorrow....

**Comment by joshmoore** [comment]
Think it's just missing the tag. I'll add one now.

**Comment by joshmoore** [comment]
I take it back. That didn't trigger anything additional; it does look like the deployments just didn't run...

**Comment by joshmoore** [comment]
Your merge here looks to have triggered the gh-pages branch to be updated:

https://github.com/ome/ome-ngff-validator/tree/gh-pages

but that didn't trigger a job for some reason.

**Pull request merged**
