### PR TITLE
Try to detect errors due to CORS when fetch fails

### LINKED ISSUE #24: Add PSA on network error that enabling CORS may fix the issue
If CORS is not enabled on the server delivering the ome-zarr data, a generic Network error message is displayed and the application errors out after requesting .zattrs.  Please consider adding text to guide to users that enabling CORS on the server might resolve the error.

image

Thanks for the excellent tool!

### PR DESCRIPTION
**Pull request by will-moore**
Fixes #24. 

See https://stackoverflow.com/questions/19325314/how-to-detect-cross-origin-cors-error-vs-other-types-of-errors-for-xmlhttpreq
Although there is no easy way to tell if a request failed due to CORS, the above question did provide a workaround: repeat the request with `no-cors` mode and if that succeeds, then the original request likely failed due to CORS.

The request error handling should now cover 3 failures:

 - no server at-all (or no connection):
 
Screenshot 2023-02-08 at 17 48 27

 - server with CORS issues:
 
Screenshot 2023-02-08 at 17 47 57

 - 404 not found:

Screenshot 2023-02-08 at 17 48 57

### CODE REVIEW

**Comment by will-moore** [comment]
Hi @AlanMWatson - could you try the deploy preview above at https://deploy-preview-25--ome-ngff-validator.netlify.app/ ?

**Comment by AlanMWatson** [comment]
Hi Will,

Thanks for working on this!
I see the message “Error Loading https://some/ome.zarr/.zattrs: Failed due to CORS issues.”
The message also appears even when 404 errors are encountered due to invalid URLs (i.e. https://not/a/path.ome.zarr/.zattrs).  Since it may not be clear what is causing the error, may I suggest changing the message to something like: “HTTP error {error_code} loading {url}: Failed due to a Network or CORS error.”

Thanks again!  This will be very helpful to others trying to troubleshoot potential network errors due to CORS not being configured server side. CORS problems are also common with neuroglancer which offers similar helpful prompts!

**Comment by will-moore** [comment]
Thanks for the testing. You're right that if you have a CORS error, this might be hiding the fact that the URL is invalid (404).
But to say "Failed due to a Network or CORS error" might lead users to assume that the Network is failing when there really is a CORS issue that must be fixed first.

I've tried to see whether I can detect a 404 when there is CORS failure (to try and give the users both pieces of info) - It *is* possible to see the 404 in the browser dev-tools but I can't access this info from JavaScript.

So I think it's safer to only report the known CORS issue and not confuse the message with other potential issues?

**Comment by will-moore** [comment]
@joshmoore this has had some testing above... - If you want to try your own CORS testing, I've been using this script to server data with CORS headers, and commenting out the `send_header()` line to test CORS failures:

```
#!/usr/bin/env python3

# From https://stackoverflow.com/questions/21956683/enable-access-control-on-simple-http-server

from http.server import HTTPServer, SimpleHTTPRequestHandler, test
import sys

class CORSRequestHandler (SimpleHTTPRequestHandler):
    def end_headers (self):
        self.send_header('Access-Control-Allow-Origin', '*')
        SimpleHTTPRequestHandler.end_headers(self)

if __name__ == '__main__':
    test(CORSRequestHandler, HTTPServer, port=int(sys.argv[1]) if len(sys.argv) > 1 else 8000)
```

Also, I added more examples to the default home page (when no source is chosen) to make it easier to test a few different files and layouts. E.g: see https://deploy-preview-25--ome-ngff-validator.netlify.app/

**Comment by joshmoore** [comment]
:+1: 

For a follow up, as this list gets longer: 

Screenshot 2023-03-09 at 17 53 54

it would probably be good to move to a drop-down, and possibly a field where someone can paste a link in rather than editing the URL.

**Comment by joshmoore** [comment]
Oh, and can there be a button that creates an issue on GitHub if there's a problem? :smile:

**Pull request merged**
