### PR TITLE
Multiple viewers

### LINKED ISSUE #19: Add links to other web-based viewers
As in the [ome-ngff-tools table ](https://ome.github.io/ome-ngff-tools/), we could also link to vtk-itk-viewer and neuroglancer, instead of only vizarr.

### PR DESCRIPTION
**Pull request by will-moore**
Fixes #19.

To test: deployed at https://deploy-preview-23--ome-ngff-validator.netlify.app/?source=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0062A/6001240.zarr 

cc @joshmoore This adds a JSON file where you can configure the various viewers for `Open with...`;

I've tried to add logos from the various viewers, but they don't all have logos - neuroglancer had no logo (just used a micro screenshot) and I used an AICS logo for their viewer, which is not ideal.

Screenshot 2023-02-17 at 10 51 21

To test:
 - Links to web-based viewers should open viewers in new tab and display the image
 - Mousing over other icons (napari, MoBIE) gives instructions and shows a 'copy' icon to copy the image URL

### CODE REVIEW

**Comment by will-moore** [comment]
@tischi How does this look for "Open with MoBIE" functionality?

@jbms - Do you have an icon I could use for neuroglancer?

@toloudis - Is this an OK icon to use for website-3d-cell-viewer? 

PR deployed at https://deploy-preview-23--ome-ngff-validator.netlify.app/?source=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0062A/6001240.zarr

**Comment by will-moore** [comment]
Other viewers we could add?:
 - webknossos - similar to napari and MoBIE examples "Login at https://webknossos.org/ and `Import your own data` > `Add remote Dataset`"
 - AGAVE - once NGFF support is in the next release
 - OMERO?! - cli import prompt with `--depth=100` tip

**Comment by toloudis** [comment]
> 
> @toloudis - Is this an OK icon to use for website-3d-cell-viewer?
> 

Yes to the allencell.org icon.

**Comment by joshmoore** [comment]
Thanks, @will-moore. Getting this in. I imagine two possible next steps might be:
* a drop-down etc. for the growing list of viewers
* a version number on the JSON :wink: e.g. if tool providers start suggesting more content.

**Pull request merged**
